services:
  domain1:
    build: ./domain1
    container_name: domain1
    restart: always
    expose:
      - "8001"
    networks:
      - web

  domain2:
    build: ./domain2
    container_name: domain2
    restart: always
    expose:
      - "8002"
    networks:
      - web

  domain3:
    build: ./domain3
    container_name: domain3
    restart: always
    expose:
      - "8003"
    networks:
      - web

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - domain1
      - domain2
      - domain3
    networks:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew --webroot -w /var/www/certbot --quiet; done'"

networks:
  web:
    driver: bridge
